// <auto-generated />
namespace BankOfBIT_KL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_NextUniqueNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_NextUniqueNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202210030339255_Added_NextUniqueNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
